# Generated by Django 3.2.8 on 2021-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='salalry_limit',
            field=models.DecimalField(db_column='nb_salary_limit', decimal_places=2, default=0, max_digits=10),
        ),
    ]
