# Generated by Django 3.2.8 on 2021-11-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211029_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('name', models.CharField(db_column='tx_name', max_length=104, unique=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='core.employee')),
            ],
            options={
                'db_table': 'employee_course',
                'unique_together': {('employee', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='employees',
            field=models.ManyToManyField(through='core.EmployeeCourse', to='core.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='courses',
            field=models.ManyToManyField(through='core.EmployeeCourse', to='core.Course'),
        ),
    ]
