# Generated by Django 3.2.8 on 2021-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211103_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(db_column='nb_salary', decimal_places=2, default=0, max_digits=10),
        ),
    ]
