# Generated by Django 3.2.8 on 2021-11-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(db_column='nb_salary', decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
